"""initial

Revision ID: 6922cd618079
Revises: 
Create Date: 2026-07-15 12:38:27.744973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6922cd618079'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_blob',
    sa.Column('blake3', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('blake3', name=op.f('pk_asset_blob'))
    )
    op.create_table('company',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('slug', name=op.f('uq_company_slug'))
    )
    op.create_table('identification_source',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identification_source')),
    sa.UniqueConstraint('slug', name=op.f('uq_identification_source_slug'))
    )
    op.create_table('job',
    sa.Column('kind', sa.Enum('NOOP', 'GOG_IMPORT', 'FETCH_METADATA', 'RENORMALIZE_METADATA', 'REFRESH_IDENTIFICATION_DATASET', 'REFRESH_IDENTIFICATION_DATASETS', 'IDENTIFY_GAME', name='jobkind', native_enum=False, length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'INTERRUPTED', name='jobstatus', native_enum=False, length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_table('library',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library')),
    sa.UniqueConstraint('slug', name=op.f('uq_library_slug'))
    )
    op.create_table('metadata_source',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('request_interval_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata_source')),
    sa.UniqueConstraint('slug', name=op.f('uq_metadata_source_slug'))
    )
    op.create_table('platform_family',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('is_pc', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_family')),
    sa.UniqueConstraint('slug', name=op.f('uq_platform_family_slug'))
    )
    op.create_table('schedule',
    sa.Column('kind', sa.Enum('NOOP', 'GOG_IMPORT', 'FETCH_METADATA', 'RENORMALIZE_METADATA', 'REFRESH_IDENTIFICATION_DATASET', 'REFRESH_IDENTIFICATION_DATASETS', 'IDENTIFY_GAME', name='jobkind', native_enum=False, length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule'))
    )
    op.create_table('secret',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_secret'))
    )
    op.create_table('series',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('slug', name=op.f('uq_series_slug'))
    )
    op.create_table('setting',
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('namespace', 'key', name=op.f('pk_setting'))
    )
    op.create_table('tag',
    sa.Column('kind', sa.Enum('GENRE', 'THEME', 'TAG', 'ENGINE', 'MODE', name='tagkind', native_enum=False, length=64), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('kind', 'slug', name=op.f('uq_tag_kind_slug'))
    )
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('company_alias',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_alias_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'alias', name=op.f('pk_company_alias'))
    )
    op.create_table('company_external_identity',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_external_identity_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['metadata_source.id'], name=op.f('fk_company_external_identity_source_id_metadata_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'source_id', name=op.f('pk_company_external_identity')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_company_external_identity_source_id_external_id'))
    )
    op.create_table('game',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('origin', sa.Enum('GOG_IMPORT', name='gameorigin', native_enum=False, length=64), nullable=True),
    sa.Column('preferred_source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name=op.f('fk_game_library_id_library')),
    sa.ForeignKeyConstraint(['preferred_source_id'], ['metadata_source.id'], name=op.f('fk_game_preferred_source_id_metadata_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game')),
    sa.UniqueConstraint('library_id', 'slug', name=op.f('uq_game_library_id_slug'))
    )
    op.create_table('metadata_record',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('api_version', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('normalized', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['metadata_source.id'], name=op.f('fk_metadata_record_source_id_metadata_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata_record')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_metadata_record_source_id_external_id'))
    )
    op.create_table('platform',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['platform_family.id'], name=op.f('fk_platform_family_id_platform_family')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform')),
    sa.UniqueConstraint('slug', name=op.f('uq_platform_slug'))
    )
    op.create_table('series_alias',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_alias_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'alias', name=op.f('pk_series_alias'))
    )
    op.create_table('series_external_identity',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_external_identity_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['metadata_source.id'], name=op.f('fk_series_external_identity_source_id_metadata_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'source_id', name=op.f('pk_series_external_identity')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_series_external_identity_source_id_external_id'))
    )
    op.create_table('tag_alias',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_tag_alias_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'alias', name=op.f('pk_tag_alias'))
    )
    op.create_table('tag_external_identity',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['metadata_source.id'], name=op.f('fk_tag_external_identity_source_id_metadata_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_tag_external_identity_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'source_id', name=op.f('pk_tag_external_identity')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_tag_external_identity_source_id_external_id'))
    )
    op.create_table('artifact',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('INSTALLER', 'PATCH', 'LANGUAGE_PACK', 'DISC', 'ROM', 'EXTRA', 'SAVE', 'MANUAL', 'OTHER', name='artifactkind', native_enum=False, length=64), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('MISSING', 'PARTIAL', 'STORED', name='artifactstatus', native_enum=False, length=64), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_artifact_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_artifact_platform_id_platform')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact'))
    )
    op.create_table('field_lock',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.Enum('TITLE', 'SORT_TITLE', 'DESCRIPTION_SHORT', 'DESCRIPTION_FULL', 'FIRST_RELEASE_DATE', 'WRAPPER', 'GAME_TYPE', 'DEVELOPERS', 'PUBLISHERS', 'SERIES', 'GENRES', 'THEMES', 'TAGS', 'ENGINES', 'MODES', 'PLATFORMS', 'RELEASE_DATES', 'RATINGS', 'SYS_REQUIREMENTS', 'ALT_NAMES', 'VIDEOS', 'COVER', 'BACKGROUND', 'LANDSCAPE', 'LOGO', 'ICON', 'SCREENSHOT', 'VIDEO_THUMBNAIL', name='fieldkey', native_enum=False, length=64), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_field_lock_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'field_key', name=op.f('pk_field_lock'))
    )
    op.create_table('game_alt_name',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_alt_name_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'name', name=op.f('pk_game_alt_name'))
    )
    op.create_table('game_asset',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('COVER', 'BACKGROUND', 'LANDSCAPE', 'LOGO', 'ICON', 'SCREENSHOT', 'VIDEO_THUMBNAIL', name='assetkind', native_enum=False, length=64), nullable=False),
    sa.Column('blob_blake3', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['blob_blake3'], ['asset_blob.blake3'], name=op.f('fk_game_asset_blob_blake3_asset_blob')),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_asset_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'kind', 'blob_blake3', name=op.f('pk_game_asset'))
    )
    op.create_table('game_company',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('DEVELOPER', 'PUBLISHER', name='companyrole', native_enum=False, length=64), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_game_company_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_company_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'company_id', 'role', name=op.f('pk_game_company'))
    )
    op.create_table('game_external_identity',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_external_identity_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['metadata_source.id'], name=op.f('fk_game_external_identity_source_id_metadata_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'source_id', name=op.f('pk_game_external_identity'))
    )
    op.create_table('game_metadata',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sort_title', sa.String(), nullable=True),
    sa.Column('description_short', sa.String(), nullable=True),
    sa.Column('description_full', sa.String(), nullable=True),
    sa.Column('first_release_date', sa.Date(), nullable=True),
    sa.Column('wrapper', sa.Enum('DOSBOX', 'SCUMMVM', name='wrapperkind', native_enum=False, length=64), nullable=True),
    sa.Column('game_type', sa.Enum('MAIN', 'DLC', 'EXPANSION', name='gametype', native_enum=False, length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_metadata_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', name=op.f('pk_game_metadata'))
    )
    op.create_table('game_platform',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_platform_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_game_platform_platform_id_platform'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'platform_id', name=op.f('pk_game_platform'))
    )
    op.create_table('game_rating',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('authority', sa.Enum('ESRB', 'PEGI', 'USK', 'CERO', 'ACB', 'CLASSIND', 'GRAC', 'CSRR', 'IGRS', name='ratingauthority', native_enum=False, length=64), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('descriptors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_rating_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'authority', name=op.f('pk_game_rating'))
    )
    op.create_table('game_release_date',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_release_date_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_game_release_date_platform_id_platform'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'platform_id', name=op.f('pk_game_release_date'))
    )
    op.create_table('game_serial',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_serial_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'value', name=op.f('pk_game_serial'))
    )
    op.create_table('game_series',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_series_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_game_series_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'series_id', name=op.f('pk_game_series'))
    )
    op.create_table('game_sys_requirement',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('os_platform_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('MINIMUM', 'RECOMMENDED', name='sysrequirementkind', native_enum=False, length=64), nullable=False),
    sa.Column('key', sa.Enum('OS', 'OS_VERSION', 'CPU', 'MEMORY', 'GPU', 'STORAGE', 'DIRECTX', 'SOUND', 'NOTES', name='sysrequirementkey', native_enum=False, length=64), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_sys_requirement_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['os_platform_id'], ['platform.id'], name=op.f('fk_game_sys_requirement_os_platform_id_platform'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'os_platform_id', 'kind', 'key', name=op.f('pk_game_sys_requirement'))
    )
    op.create_table('game_tag',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_tag_game_id_game'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_game_tag_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'tag_id', name=op.f('pk_game_tag'))
    )
    op.create_table('game_video',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_game_video_game_id_game'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'url', name=op.f('pk_game_video'))
    )
    op.create_table('identification_dataset',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=True),
    sa.Column('dataset_url', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_identification_dataset_platform_id_platform')),
    sa.ForeignKeyConstraint(['source_id'], ['identification_source.id'], name=op.f('fk_identification_dataset_source_id_identification_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identification_dataset')),
    sa.UniqueConstraint('slug', name=op.f('uq_identification_dataset_slug'))
    )
    op.create_table('source_asset',
    sa.Column('metadata_record_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('COVER', 'BACKGROUND', 'LANDSCAPE', 'LOGO', 'ICON', 'SCREENSHOT', 'VIDEO_THUMBNAIL', name='assetkind', native_enum=False, length=64), nullable=False),
    sa.Column('blob_blake3', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blob_blake3'], ['asset_blob.blake3'], name=op.f('fk_source_asset_blob_blake3_asset_blob')),
    sa.ForeignKeyConstraint(['metadata_record_id'], ['metadata_record.id'], name=op.f('fk_source_asset_metadata_record_id_metadata_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metadata_record_id', 'kind', 'blob_blake3', name=op.f('pk_source_asset'))
    )
    op.create_table('file',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('relative_path', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('blake3', sa.String(), nullable=True),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('sha1', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('crc32', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], name=op.f('fk_file_artifact_id_artifact'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file'))
    )
    op.create_table('identification_signature',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('md5', sa.String(), nullable=True),
    sa.Column('sha1', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('crc32', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['identification_dataset.id'], name=op.f('fk_identification_signature_dataset_id_identification_dataset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identification_signature')),
    sa.UniqueConstraint('dataset_id', 'game_name', 'file_name', name=op.f('uq_identification_signature_dataset_id_game_name_file_name'))
    )
    op.create_index('ix_identification_signature_crc32', 'identification_signature', ['crc32'], unique=False)
    op.create_index('ix_identification_signature_md5', 'identification_signature', ['md5'], unique=False)
    op.create_index('ix_identification_signature_sha1', 'identification_signature', ['sha1'], unique=False)
    op.create_index('ix_identification_signature_sha256', 'identification_signature', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identification_signature_sha256', table_name='identification_signature')
    op.drop_index('ix_identification_signature_sha1', table_name='identification_signature')
    op.drop_index('ix_identification_signature_md5', table_name='identification_signature')
    op.drop_index('ix_identification_signature_crc32', table_name='identification_signature')
    op.drop_table('identification_signature')
    op.drop_table('file')
    op.drop_table('source_asset')
    op.drop_table('identification_dataset')
    op.drop_table('game_video')
    op.drop_table('game_tag')
    op.drop_table('game_sys_requirement')
    op.drop_table('game_series')
    op.drop_table('game_serial')
    op.drop_table('game_release_date')
    op.drop_table('game_rating')
    op.drop_table('game_platform')
    op.drop_table('game_metadata')
    op.drop_table('game_external_identity')
    op.drop_table('game_company')
    op.drop_table('game_asset')
    op.drop_table('game_alt_name')
    op.drop_table('field_lock')
    op.drop_table('artifact')
    op.drop_table('tag_external_identity')
    op.drop_table('tag_alias')
    op.drop_table('series_external_identity')
    op.drop_table('series_alias')
    op.drop_table('platform')
    op.drop_table('metadata_record')
    op.drop_table('game')
    op.drop_table('company_external_identity')
    op.drop_table('company_alias')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('setting')
    op.drop_table('series')
    op.drop_table('secret')
    op.drop_table('schedule')
    op.drop_table('platform_family')
    op.drop_table('metadata_source')
    op.drop_table('library')
    op.drop_table('job')
    op.drop_table('identification_source')
    op.drop_table('company')
    op.drop_table('asset_blob')
    # ### end Alembic commands ###
