/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Alternative display name.
 */
export interface AltNameEntry {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
  comment?: string | null
}
