/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

export type ArtifactStatus = (typeof ArtifactStatus)[keyof typeof ArtifactStatus]

export const ArtifactStatus = {
  missing: "missing",
  partial: "partial",
  stored: "stored",
} as const
