/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactKind } from "./artifactKind"
import type { ArtifactStatus } from "./artifactStatus"
import type { FileOut } from "./fileOut"

/**
 * Artifact with its files.
 */
export interface ArtifactOut {
  id: string
  kind: ArtifactKind
  platform_slug: string | null
  language: string | null
  version: string | null
  status: ArtifactStatus
  total_size: number | null
  name: string | null
  files: FileOut[]
}
