/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * One candidate image (visible/ordinal null until it is a game_asset row).
 */
export interface AssetCandidateOut {
  blake3: string
  url: string
  mime: string
  size: number
  width: number | null
  height: number | null
  source_slugs: string[]
  visible: boolean | null
  ordinal: number | null
}
