/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Ordered visible set for one asset kind.
 */
export interface AssetKindPut {
  blobs: string[]
}
