/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Dataset settings patch.
 */
export interface DatasetPatch {
  enabled?: boolean | null
}
