/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Dataset-discovery result.
 */
export interface DiscoverDatasetsOut {
  dataset_count: number
}
