/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Vocabulary entity reference.
 */
export interface EntityOut {
  slug: string
  name: string
}
