/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * External catalog identity.
 */
export interface ExternalIdentityOut {
  source_slug: string
  external_id: string
}
