/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Digests computed while the upload streamed to staging.
 */
export interface FileHashes {
  blake3: string
  md5: string
  sha1: string
  sha256: string
  crc32: string
}
