/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { SignatureMatchOut } from "./signatureMatchOut"

/**
 * Stored file (matches = its derived identification matches).
 */
export interface FileOut {
  id: string
  relative_path: string | null
  size: number | null
  blake3: string | null
  matches?: SignatureMatchOut[]
}
