/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { Game } from "./game"

/**
 * Finalize result: the created game, plus the identify job when a signature seeded it.
 */
export interface FinalizeOut {
  game: Game
  identify_job_id: string | null
}
