/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactKind } from "./artifactKind"

/**
 * Finalize request: create the game + artifact from a staged file.
 */
export interface FinalizeRequest {
  /** @pattern ^[a-f0-9]{32}$ */
  stage_id: string
  library_id: string
  /**
   * @minLength 1
   * @maxLength 64
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  slug: string
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string
  kind: ArtifactKind
  chosen_signature_id?: string | null
}
