/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

export type GameType = (typeof GameType)[keyof typeof GameType]

export const GameType = {
  main: "main",
  dlc: "dlc",
  expansion: "expansion",
} as const
