/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { GameOrigin } from "./gameOrigin"
import type { GameType } from "./gameType"
import type { WrapperKind } from "./wrapperKind"

/**
 * Game (list shape).
 */
export interface Game {
  id: string
  library_id: string
  slug: string
  origin: GameOrigin | null
  preferred_source_id: string | null
  created_at: string
  updated_at: string
  title: string
  sort_title: string | null
  description_short: string | null
  description_full: string | null
  first_release_date: string | null
  wrapper: WrapperKind | null
  game_type: GameType | null
  resolved_at: string | null
  cover_url: string | null
  landscape_url: string | null
}
