/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Resolved display assets beyond the flat cover/landscape pair.
 */
export interface GameAssetsOut {
  screenshots: string[]
}
