/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { AssetCandidateOut } from "./assetCandidateOut"

/**
 * Candidate pool per asset kind, with current selection state.
 */
export interface GameAssetCandidates {
  cover: AssetCandidateOut[]
  background: AssetCandidateOut[]
  landscape: AssetCandidateOut[]
  logo: AssetCandidateOut[]
  icon: AssetCandidateOut[]
  screenshot: AssetCandidateOut[]
  video_thumbnail: AssetCandidateOut[]
}
