/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { GameType } from "./gameType"
import type { WrapperKind } from "./wrapperKind"

/**
 * Game create request.
 */
export interface GameCreate {
  library_id: string
  /**
   * @minLength 1
   * @maxLength 64
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  slug: string
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string
  sort_title?: string | null
  description_short?: string | null
  description_full?: string | null
  first_release_date?: string | null
  wrapper?: WrapperKind | null
  game_type?: GameType | null
}
