/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

export type GameOrigin = (typeof GameOrigin)[keyof typeof GameOrigin]

export const GameOrigin = {
  gog_import: "gog_import",
} as const
