/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { AltNameEntry } from "./altNameEntry"
import type { ArtifactOut } from "./artifactOut"
import type { EntityOut } from "./entityOut"
import type { ExternalIdentityOut } from "./externalIdentityOut"
import type { FieldKey } from "./fieldKey"
import type { GameAssetsOut } from "./gameAssetsOut"
import type { GameOrigin } from "./gameOrigin"
import type { GameType } from "./gameType"
import type { PlatformOut } from "./platformOut"
import type { RatingEntry } from "./ratingEntry"
import type { ReleaseDateEntry } from "./releaseDateEntry"
import type { SerialEntry } from "./serialEntry"
import type { VideoOut } from "./videoOut"
import type { WrapperKind } from "./wrapperKind"

/**
 * Full game detail.
 */
export interface GameDetail {
  id: string
  library_id: string
  slug: string
  origin: GameOrigin | null
  preferred_source_id: string | null
  created_at: string
  updated_at: string
  title: string
  sort_title: string | null
  description_short: string | null
  description_full: string | null
  first_release_date: string | null
  wrapper: WrapperKind | null
  game_type: GameType | null
  resolved_at: string | null
  cover_url: string | null
  landscape_url: string | null
  locks: FieldKey[]
  artifacts: ArtifactOut[]
  assets: GameAssetsOut
  developers: EntityOut[]
  publishers: EntityOut[]
  series: EntityOut[]
  genres: EntityOut[]
  themes: EntityOut[]
  tags: EntityOut[]
  engines: EntityOut[]
  modes: EntityOut[]
  platforms: PlatformOut[]
  release_dates: ReleaseDateEntry[]
  ratings: RatingEntry[]
  alt_names: AltNameEntry[]
  videos: VideoOut[]
  serials: SerialEntry[]
  external_identities: ExternalIdentityOut[]
}
