/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { AltNameEntry } from "./altNameEntry"
import type { GameType } from "./gameType"
import type { RatingEntry } from "./ratingEntry"
import type { ReleaseDateEntry } from "./releaseDateEntry"
import type { SerialEntry } from "./serialEntry"
import type { VideoPut } from "./videoPut"
import type { WrapperKind } from "./wrapperKind"

/**
 * Game patch request. Collections are replace-arrays: omit = untouched,
 * [] = clear; the fields typed without null reject explicit null.
 */
export interface GamePatch {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string
  sort_title?: string | null
  description_short?: string | null
  description_full?: string | null
  first_release_date?: string | null
  wrapper?: WrapperKind | null
  game_type?: GameType | null
  preferred_source_id?: string | null
  library_id?: string
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  developers?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  publishers?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  series?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  genres?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  themes?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  tags?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  engines?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  modes?: string[]
  /**
   * @items.minLength 1
   * @items.maxLength 255
   */
  platforms?: string[]
  release_dates?: ReleaseDateEntry[]
  ratings?: RatingEntry[]
  alt_names?: AltNameEntry[]
  videos?: VideoPut[]
  serials?: SerialEntry[]
}
