/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Auth-code exchange request.
 */
export interface GogAuthRequest {
  /** @minLength 1 */
  code: string
}
