/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Import request for one owned GOG game.
 */
export interface GogImportRequest {
  gog_id: number
  library_id: string
}
