/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Set a game's identity in one external catalog.
 */
export interface IdentityPut {
  /**
   * @minLength 1
   * @maxLength 255
   */
  external_id: string
}
