/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Twitch developer-app credentials for IGDB.
 */
export interface IgdbCredentialsPut {
  /** @minLength 1 */
  client_id: string
  /** @minLength 1 */
  client_secret: string
}
