/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { JobKind } from "./jobKind"
import type { JobPayload } from "./jobPayload"
import type { JobProgress } from "./jobProgress"
import type { JobResult } from "./jobResult"
import type { JobStatus } from "./jobStatus"

/**
 * Job with kind-typed JSON payload/result (typed per kind client-side).
 */
export interface Job {
  id: string
  kind: JobKind
  status: JobStatus
  payload: JobPayload
  progress: JobProgress
  result: JobResult
  error: string | null
  created_at: string
  updated_at: string
}
