/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

export type JobKind = (typeof JobKind)[keyof typeof JobKind]

export const JobKind = {
  gog_import: "gog_import",
  fetch_metadata: "fetch_metadata",
  renormalize_metadata: "renormalize_metadata",
  refresh_identification_dataset: "refresh_identification_dataset",
  refresh_identification_datasets: "refresh_identification_datasets",
  identify_game: "identify_game",
} as const
