/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { JobStageStatus } from "./jobStageStatus"

/**
 * One stage of a job's typed progress.
 */
export interface JobStage {
  key: string
  label: string
  group?: string | null
  status?: JobStageStatus
  error?: string | null
  bytes_done?: number | null
  bytes_total?: number | null
}
