/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Game library.
 */
export interface Library {
  id: string
  slug: string
  name: string
  created_at: string
  updated_at: string
}
