/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Library create request.
 */
export interface LibraryCreate {
  /**
   * @minLength 1
   * @maxLength 64
   * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
   */
  slug: string
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string
}
