/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

export type ListLibrariesParams = {
  /**
   * Opaque cursor from next_cursor.
   */
  cursor?: string | null
  /**
   * Page size.
   * @minimum 1
   * @maximum 200
   */
  limit?: number
}
