/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata source patch request.
 */
export interface MetadataSourcePatch {
  enabled?: boolean
  priority?: number
  request_interval_ms?: number | null
}
