/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata source registry entry.
 */
export interface MetadataSource {
  id: string
  slug: string
  name: string
  enabled: boolean
  required: boolean
  priority: number
  request_interval_ms: number | null
  searchable?: boolean
}
