/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * An owned GOG game, flagged when it's already in the library.
 */
export interface OwnedGameOut {
  gog_id: number
  title: string
  slug: string
  image_url: string | null
  imported: boolean
  complete: boolean
}
