/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { Library } from "./library"

export interface PageLibrary {
  items: Library[]
  next_cursor?: string | null
}
