/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { Job } from "./job"

export interface PageJob {
  items: Job[]
  next_cursor?: string | null
}
