/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { Game } from "./game"

export interface PageGame {
  items: Game[]
  next_cursor?: string | null
}
