/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Platform with its family.
 */
export interface PlatformOut {
  slug: string
  name: string
  family_slug: string
}
