/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

export type RatingAuthority = (typeof RatingAuthority)[keyof typeof RatingAuthority]

export const RatingAuthority = {
  esrb: "esrb",
  pegi: "pegi",
  usk: "usk",
  cero: "cero",
  acb: "acb",
  classind: "classind",
  grac: "grac",
  csrr: "csrr",
  igrs: "igrs",
} as const
