/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { RatingAuthority } from "./ratingAuthority"

/**
 * One authority's age rating.
 */
export interface RatingEntry {
  authority: RatingAuthority
  /**
   * @minLength 1
   * @maxLength 255
   */
  value: string
  descriptors?: string[]
}
