/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-platform release date.
 */
export interface ReleaseDateEntry {
  /**
   * @minLength 1
   * @maxLength 255
   */
  platform: string
  date: string
}
