/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * One catalog-search candidate.
 */
export interface SearchCandidateOut {
  external_id: string
  name: string
  year: number | null
}
