/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Secret put request.
 */
export interface SecretPut {
  /**
   * @minLength 1
   * @maxLength 10000
   */
  value: string
}
