/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Serial number row.
 */
export interface SerialEntry {
  /**
   * @minLength 1
   * @maxLength 255
   */
  value: string
  comment?: string | null
}
