/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * A file's identification-signature match (derived).
 */
export interface SignatureMatchOut {
  signature_id: string
  game_name: string
  file_name: string
  category: string | null
  dataset_name: string
  source_slug: string
}
