/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */
import type { ArtifactKind } from "./artifactKind"
import type { FileHashes } from "./fileHashes"
import type { SignatureMatchOut } from "./signatureMatchOut"

/**
 * Staged upload.
 */
export interface StageOut {
  stage_id: string
  filename: string
  size: number
  hashes: FileHashes
  suggested_slug: string
  suggested_kind: ArtifactKind
  matches: SignatureMatchOut[]
}
