/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Video entry as writable via PATCH (a URL is required).
 */
export interface VideoPut {
  /**
   * @minLength 1
   * @maxLength 255
   */
  provider: string
  /**
   * @minLength 1
   * @maxLength 2048
   */
  url: string
  video_id?: string | null
  name?: string | null
}
