/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * External video.
 */
export interface VideoOut {
  provider: string
  url: string
  video_id: string | null
  name: string | null
}
