/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

export type WrapperKind = (typeof WrapperKind)[keyof typeof WrapperKind]

export const WrapperKind = {
  dosbox: "dosbox",
  scummvm: "scummvm",
} as const
