/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Silo
 * OpenAPI spec version: 0.1.0
 */

/**
 * One member of a stored zip file.
 */
export interface ZipMemberOut {
  path: string
  size: number
}
