/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as GogIndexRouteImport } from './routes/gog/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as LibrariesLibraryIdRouteImport } from './routes/libraries/$libraryId'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GogIndexRoute = GogIndexRouteImport.update({
  id: '/gog/',
  path: '/gog/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdRoute = LibrariesLibraryIdRouteImport.update({
  id: '/libraries/$libraryId',
  path: '/libraries/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/games/': typeof GamesIndexRoute
  '/gog/': typeof GogIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/upload/': typeof UploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/games': typeof GamesIndexRoute
  '/gog': typeof GogIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/upload': typeof UploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/libraries/$libraryId': typeof LibrariesLibraryIdRoute
  '/games/': typeof GamesIndexRoute
  '/gog/': typeof GogIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/upload/': typeof UploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/$gameId'
    | '/libraries/$libraryId'
    | '/games/'
    | '/gog/'
    | '/jobs/'
    | '/settings/'
    | '/upload/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/$gameId'
    | '/libraries/$libraryId'
    | '/games'
    | '/gog'
    | '/jobs'
    | '/settings'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/games/$gameId'
    | '/libraries/$libraryId'
    | '/games/'
    | '/gog/'
    | '/jobs/'
    | '/settings/'
    | '/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  LibrariesLibraryIdRoute: typeof LibrariesLibraryIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GogIndexRoute: typeof GogIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UploadIndexRoute: typeof UploadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gog/': {
      id: '/gog/'
      path: '/gog'
      fullPath: '/gog/'
      preLoaderRoute: typeof GogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId': {
      id: '/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof LibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  LibrariesLibraryIdRoute: LibrariesLibraryIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  GogIndexRoute: GogIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UploadIndexRoute: UploadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
